FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

RUN pip install diffusers && \
    pip install fire && \
    pip install einops && \
    pip install torchvision && \
    pip install scipy && \
    pip install transformers